services:
  app_proxy:
    image: alpine:3.20
    command: ["sleep", "infinity"]
    restart: "no"

  indexer-ui-api:
    build: ./api

  frontend:
    build: ./frontend
    ports:
      - "${APP_KASPA_INDEXER_UI_PORT}:${APP_KASPA_INDEXER_UI_PORT}"
