version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: elldeeone-kas-rusty-kaspad_frontend_1
      APP_PORT: 4321

  frontend:
    image: elldee/kaspa-frontend:v0.3.1@sha256:bf9dc2189df37561a9d81e1368c935d1d94c7e3cd57da8d759cb83be6ea3b44a
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - kaspa-api
  
  kaspa-api:
    image: elldee/kaspa-api:v0.3.1@sha256:1ddc6fd181aab9bd2679769233766dcfaba2030e52f3972fc15acad06297bc8a
    restart: on-failure
    stop_grace_period: 1m
    environment:
      KASPAD_HOST: kaspad
      KASPAD_RPC_PORT: 18110
      KASPAD_CONTAINER_NAME: elldeeone-kas-rusty-kaspad_kaspad_1
    volumes:
      - ${APP_DATA_DIR}/logs:/logs:ro  # For log parsing
    depends_on:
      - kaspad

  kaspad:
    image: kaspanet/rusty-kaspad:v1.0.1@sha256:5bc3195c2cd2d171885781ed55ead9485d93c7bd7b784d46e9e393c96757fe22
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/logs:/logs
      - ${APP_DATA_DIR}/kaspad-entrypoint.sh:/entrypoint.sh:ro
    ports:
      - 16110:16110  # GRPC
      - 16111:16111  # P2P
      - 17110:17110  # WRPC (Borsh)
      - 18110:18110  # WRPC (JSON)
    entrypoint: /entrypoint.sh