services:
  app_proxy:
    environment:
      APP_HOST: kaspa-node_frontend_1
      APP_PORT: 4321

  frontend:
    image: elldee/kaspa-frontend:v0.3.1@sha256:bf9dc2189df37561a9d81e1368c935d1d94c7e3cd57da8d759cb83be6ea3b44a
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - kaspa-api
  
  kaspa-api:
    image: elldee/kaspa-api:v0.3.1@sha256:1ddc6fd181aab9bd2679769233766dcfaba2030e52f3972fc15acad06297bc8a
    restart: on-failure
    stop_grace_period: 1m
    environment:
      KASPAD_HOST: kaspad
      KASPAD_RPC_PORT: 18110
      KASPAD_CONTAINER_NAME: kaspa-node_kaspad_1
    volumes:
      - ${APP_DATA_DIR}/logs:/logs:ro  # For log parsing
    depends_on:
      - kaspad

  kaspad:
    image: supertypo/rusty-kaspad:48f4d03
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/logs
    ports:
      - 16110:16110  # GRPC
      - 16111:16111  # P2P
      - 17110:17110  # WRPC (Borsh)
      - 18110:18110  # WRPC (JSON)
    command: >
      kaspad
      --appdir=/app/data
      --yes
      --nologfiles
      --disable-upnp
      --utxoindex
      --rpclisten=0.0.0.0:16110
      --rpclisten-borsh=0.0.0.0:17110
      --rpclisten-json=0.0.0.0:18110
