services:
  frontend:
    image: dennitzo/kaspa-node-ui:latest
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - kaspa-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "19112:19112"
  
  kaspa-api:
    image: dennitzo/kaspa-node-api:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      APP_COMPOSE_PROJECT: kaspa-node
      APP_KASPAD_SERVICE: kaspad
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - kaspad
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kaspad:
    image: supertypo/rusty-kaspad:48f4d03
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}:/app/data
      - ${APP_DATA_DIR}/logs:/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 16110:16110  # GRPC
      - 16111:16111  # P2P
      - 17110:17110  # WRPC (Borsh)
      - 18110:18110  # WRPC (JSON)
    command: >
      kaspad
      --appdir=/app/data
      --yes
      --nologfiles
      --disable-upnp
      --utxoindex
      --rpclisten=0.0.0.0:16110
      --rpclisten-borsh=0.0.0.0:17110
      --rpclisten-json=0.0.0.0:18110
